// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftmvrmneykmqukznojbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0bXZybW5leWttcXVrem5vamJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNzMyMTMsImV4cCI6MjA1Nzk0OTIxM30.MRpXsYt96Q2USjgZrs-qhV92ZaT5mJoakp8IuXzwFTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);